### ISSUE TITLE
Feature: Add support for windows platform

### ISSUE THREAD

**Issue by nimDevOps** [jjasghar/powercli_install#1]
Nice cookbook for debian and rhel, I think it would be great to add few lines under **when 'windows'**   
Then the cookbook will be universal 👍 .

**Comment by jjasghar** [comment]
Ha! very good point. I'll make it happen asap.

**Comment by jjasghar** [comment]
Released with 2f97446 :) thanks for the suggestion!

**Comment by nimDevOps** [comment]
Thanks a lot! I tried this on WS2016 and it works out of the box. I will use this cookbook to bring PowerCLI to my IaC build machine (VM building VMs on via vcenter driver).

**Comment by jjasghar** [comment]
Awesome!
